name: "Renpy Text Linter"
description: "Проверяет орфографию в указанных файлах с помощью кастомного скрипта"
inputs:
  files:
    description: "Список файлов для проверки, разделённых пробелами"
    required: true
    type: string
  exclusions:
    description: "Путь к файлу исключений"
    required: false
    type: string
  output_type:
    description: "Формат вывода"
    required: false
    type: string
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.files }}
    - --exclusions
    - ${{ inputs.exclusions}}
    - --output-type
    - ${{ inputs.output_type }}